/* DevFit curated food database — offline, Malaysia-first.
   Always available (no API, no rate limit, works offline) and ranked above
   USDA / Open Food Facts so local + staple foods surface first.

   Values are PER 100g (or per 100ml for drinks). `serving` = default grams.
   `servings` = named size chips shown in the picker (no weight machine needed).

   Sources: USDA FoodData Central for generic/whole foods;
   HPB Singapore / Tee et al. Nutrient Composition of Malaysian Foods for
   local dishes. Packaged values from product nutrition labels.
   Edit with the Edit tool only (UTF-8). */
(function(){
  const F = [

    // ════════ PROTEINS — poultry ════════
    {name:'Chicken Breast (skinless, cooked)', serving:150, cal:165, p:31, c:0, f:3.6,
     servings:[{n:'½ piece (100g)',g:100},{n:'1 small piece',g:130},{n:'1 medium piece',g:170},{n:'1 large piece',g:220}],
     tags:'poultry lean protein ayam'},
    {name:'Chicken Thigh (skinless, cooked)', serving:120, cal:209, p:26, c:0, f:10.9,
     servings:[{n:'1 small thigh',g:100},{n:'1 thigh',g:130},{n:'1 large thigh',g:160}],
     tags:'poultry protein ayam'},
    {name:'Chicken Drumstick (cooked, with skin)', serving:100, cal:216, p:27, c:0, f:11.5,
     servings:[{n:'1 small drumstick',g:80},{n:'1 drumstick',g:110},{n:'1 large drumstick',g:140}],
     tags:'poultry ayam'},
    {name:'Chicken Wing (cooked, with skin)', serving:90, cal:266, p:30, c:0, f:15.8,
     servings:[{n:'1 wing',g:90},{n:'2 wings',g:180},{n:'3 wings',g:270}],
     tags:'poultry ayam kepak'},
    {name:'Chicken (whole, roasted, with skin)', serving:120, cal:239, p:27, c:0, f:14,
     servings:[{n:'1 palm-size',g:100},{n:'1 small piece',g:150},{n:'1 large piece',g:200}],
     tags:'poultry ayam'},

    // ════════ PROTEINS — eggs ════════
    {name:'Egg (whole, boiled / half-boiled)', serving:50, cal:155, p:13, c:1.1, f:11,
     servings:[{n:'1 small egg',g:38},{n:'1 medium egg',g:44},{n:'1 large egg',g:50},{n:'2 eggs',g:100},{n:'3 eggs',g:150}],
     tags:'protein telur breakfast rebus'},
    {name:'Egg (fried, sunny-side up)', serving:50, cal:196, p:14, c:0.8, f:15,
     servings:[{n:'1 egg',g:50},{n:'2 eggs',g:100},{n:'3 eggs',g:150}],
     tags:'protein telur goreng'},
    {name:'Egg White', serving:33, cal:52, p:10.9, c:0.7, f:0.2,
     servings:[{n:'1 egg white',g:33},{n:'2 egg whites',g:66},{n:'3 egg whites',g:100}],
     tags:'protein telur putih'},
    {name:'Century Egg (pei dan)', serving:70, cal:135, p:13, c:1, f:8,
     servings:[{n:'1 century egg',g:70},{n:'2 eggs',g:140}],
     tags:'chinese preserved egg pei dan telur'},
    {name:'Salted Egg (telur masin)', serving:70, cal:185, p:13, c:0.6, f:14,
     servings:[{n:'1 salted egg',g:70},{n:'2 eggs',g:140}],
     tags:'salted egg telur masin'},

    // ════════ PROTEINS — red meat ════════
    {name:'Beef (sirloin, lean, cooked)', serving:120, cal:212, p:30, c:0, f:10,
     servings:[{n:'1 thin slice',g:80},{n:'1 palm-size',g:120},{n:'1 large piece',g:180}],
     tags:'red meat protein daging'},
    {name:'Beef (minced, cooked)', serving:120, cal:254, p:26, c:0, f:16,
     servings:[{n:'½ cup',g:80},{n:'1 cup',g:150}],
     tags:'red meat daging kisar'},
    {name:'Pork (loin, lean, cooked)', serving:120, cal:242, p:27, c:0, f:14,
     servings:[{n:'1 thin slice',g:80},{n:'1 piece',g:120},{n:'1 large piece',g:180}],
     tags:'pork protein babi'},
    {name:'Pork Belly (cooked)', serving:80, cal:518, p:9, c:0, f:53,
     servings:[{n:'2 thin slices',g:60},{n:'3 slices',g:80},{n:'100g',g:100}],
     tags:'pork fatty babi'},
    {name:'Lamb / Mutton (cooked)', serving:120, cal:294, p:25, c:0, f:21,
     servings:[{n:'1 piece (small)',g:100},{n:'1 piece',g:130},{n:'100g',g:100}],
     tags:'red meat kambing'},

    // ════════ PROTEINS — processed / other ════════
    {name:'Sausage (chicken/beef)', serving:50, cal:255, p:11, c:3, f:22,
     servings:[{n:'1 sausage',g:50},{n:'2 sausages',g:100}],
     tags:'processed protein sausage sosej'},
    {name:'Luncheon Meat (spam / maling)', serving:56, cal:290, p:12, c:4, f:26,
     servings:[{n:'1 slice',g:40},{n:'2 slices',g:80},{n:'3 slices',g:120}],
     tags:'processed canned meat spam maling'},
    {name:'Ham (sliced)', serving:30, cal:149, p:17, c:2, f:8,
     servings:[{n:'1 slice',g:30},{n:'2 slices',g:60},{n:'3 slices',g:90}],
     tags:'processed ham deli'},
    {name:'Bak Kwa (BBQ pork jerky)', serving:30, cal:365, p:20, c:38, f:14,
     servings:[{n:'1 slice',g:30},{n:'2 slices',g:60}],
     tags:'bbq pork jerky bak kwa chinese new year snack'},

    // ════════ SEAFOOD ════════
    {name:'Salmon (cooked)', serving:150, cal:208, p:28, c:0, f:10,
     servings:[{n:'½ fillet (100g)',g:100},{n:'1 fillet',g:170}],
     tags:'fish omega3 protein'},
    {name:'Tuna (canned in water)', serving:85, cal:116, p:26, c:0, f:1,
     servings:[{n:'½ can',g:85},{n:'1 can (185g)',g:185}],
     tags:'fish canned tuna protein'},
    {name:'Mackerel / Ikan Tenggiri (cooked)', serving:150, cal:139, p:19, c:0, f:7,
     servings:[{n:'1 small fillet',g:100},{n:'1 fillet',g:150},{n:'1 large fillet',g:200}],
     tags:'fish mackerel tenggiri ikan'},
    {name:'Tilapia / Ikan Tilapia (cooked)', serving:150, cal:128, p:26, c:0, f:2.7,
     servings:[{n:'1 small fish',g:120},{n:'1 fish',g:200}],
     tags:'fish tilapia ikan'},
    {name:'Red Snapper / Ikan Merah (steamed/grilled)', serving:150, cal:100, p:20, c:0, f:2,
     servings:[{n:'1 portion',g:150},{n:'1 large portion',g:200}],
     tags:'fish snapper ikan merah'},
    {name:'Sea Bass / Ikan Siakap (steamed)', serving:150, cal:97, p:18, c:0, f:2.5,
     servings:[{n:'1 portion',g:150},{n:'1 large portion',g:200}],
     tags:'fish sea bass siakap ikan'},
    {name:'Pomfret / Ikan Bawal (fried/grilled)', serving:150, cal:130, p:20, c:0, f:5,
     servings:[{n:'1 small fish',g:120},{n:'1 fish',g:180}],
     tags:'fish pomfret bawal ikan'},
    {name:'Stingray / Ikan Pari (grilled/sambal)', serving:150, cal:138, p:20, c:0, f:6,
     servings:[{n:'1 portion',g:150},{n:'1 large portion',g:220}],
     tags:'fish stingray pari ikan bakar'},
    {name:'Catfish / Ikan Keli (fried)', serving:150, cal:132, p:18, c:0, f:6,
     servings:[{n:'1 small fish',g:100},{n:'1 fish',g:150}],
     tags:'fish catfish keli ikan'},
    {name:'Sardines (canned in tomato sauce)', serving:90, cal:165, p:18, c:2, f:9,
     servings:[{n:'½ can',g:90},{n:'1 can (155g)',g:155}],
     tags:'fish canned sardine ikan sardin'},
    {name:'Dried Fish / Ikan Masin', serving:30, cal:284, p:45, c:0, f:10,
     servings:[{n:'1 small piece',g:20},{n:'1 piece',g:35},{n:'2 pieces',g:60}],
     tags:'dried fish ikan masin salt'},
    {name:'Dried Shrimp / Udang Kering', serving:15, cal:306, p:59, c:0.7, f:4,
     servings:[{n:'1 tbsp',g:10},{n:'2 tbsp',g:20}],
     tags:'dried shrimp udang kering condiment'},
    {name:'Prawn / Udang (medium, cooked)', serving:100, cal:99, p:21, c:0.2, f:1,
     servings:[{n:'5 prawns (small)',g:50},{n:'5 prawns (medium)',g:80},{n:'5 prawns (large)',g:120}],
     tags:'prawn shrimp seafood udang'},
    {name:'Squid / Sotong (cooked, plain)', serving:100, cal:92, p:16, c:3, f:1.4,
     servings:[{n:'1 small portion',g:80},{n:'1 portion',g:120}],
     tags:'squid sotong seafood'},
    {name:'Crab (steamed)', serving:200, cal:97, p:19, c:0, f:2,
     servings:[{n:'1 medium crab',g:200},{n:'1 large crab',g:350}],
     tags:'crab seafood ketam'},
    {name:'Cockles / Kerang (cooked)', serving:100, cal:74, p:12, c:4, f:1,
     servings:[{n:'½ cup (cooked)',g:80},{n:'1 cup',g:150}],
     tags:'cockles kerang seafood shellfish'},
    {name:'Fish Cake / Kek Ikan (sliced)', serving:80, cal:115, p:14, c:4, f:4,
     servings:[{n:'2 slices',g:60},{n:'3 slices',g:80},{n:'4 slices',g:120}],
     tags:'fish cake kek ikan processed'},
    {name:'Fish Ball (4 pcs)', serving:60, cal:70, p:12, c:5, f:1,
     servings:[{n:'4 balls (small)',g:60},{n:'4 balls (large)',g:80}],
     tags:'fish ball fish cake seafood'},

    // ════════ DAIRY ════════
    {name:'Full Cream Milk', serving:250, cal:61, p:3.2, c:4.8, f:3.3,
     servings:[{n:'1 small glass (200ml)',g:200},{n:'1 glass (250ml)',g:250},{n:'1 large glass (350ml)',g:350}],
     tags:'dairy milk susu full cream'},
    {name:'Low Fat Milk (2%)', serving:250, cal:50, p:3.4, c:5, f:2,
     servings:[{n:'1 glass (250ml)',g:250},{n:'1 large glass (350ml)',g:350}],
     tags:'dairy milk susu low fat'},
    {name:'Skim Milk', serving:250, cal:34, p:3.4, c:5, f:0.1,
     servings:[{n:'1 glass (250ml)',g:250}],
     tags:'dairy milk susu skim'},
    {name:'Yogurt (plain, full fat)', serving:150, cal:61, p:3.5, c:4.7, f:3.3,
     servings:[{n:'1 small tub',g:125},{n:'1 tub',g:150},{n:'1 large tub',g:200}],
     tags:'dairy yogurt yoghurt plain'},
    {name:'Greek Yogurt (plain)', serving:150, cal:59, p:10, c:3.6, f:0.4,
     servings:[{n:'1 tub (100g)',g:100},{n:'1 large tub (150g)',g:150}],
     tags:'dairy greek yogurt high protein'},
    {name:'Cheese (cheddar)', serving:30, cal:404, p:25, c:1.3, f:33,
     servings:[{n:'1 slice',g:21},{n:'1 thick slice',g:30},{n:'30g',g:30}],
     tags:'dairy cheese cheddar'},
    {name:'Cream Cheese', serving:30, cal:342, p:6, c:4, f:34,
     servings:[{n:'1 tbsp',g:15},{n:'2 tbsp',g:30}],
     tags:'dairy cream cheese spread'},
    {name:'Butter / Mentega', serving:10, cal:717, p:0.9, c:0.1, f:81,
     servings:[{n:'1 tsp',g:5},{n:'1 tbsp',g:14}],
     tags:'dairy butter fat mentega'},
    {name:'Condensed Milk (sweetened)', serving:15, cal:327, p:7, c:55, f:8,
     servings:[{n:'1 tsp',g:7},{n:'1 tbsp',g:15},{n:'2 tbsp',g:30}],
     tags:'condensed milk susu pekat manis'},
    {name:'Marigold Natural Yogurt', brand:'Marigold', serving:150, cal:63, p:4, c:8, f:1.8,
     servings:[{n:'1 tub (125g)',g:125},{n:'1 large tub (150g)',g:150}],
     tags:'yogurt plain yoghurt marigold dairy'},
    {name:'Vitagen (per bottle 125ml)', brand:'Vitagen', serving:125, cal:72, p:1.5, c:14, f:0.3,
     servings:[{n:'1 bottle',g:125},{n:'2 bottles',g:250}],
     tags:'vitagen yakult probiotic drink dairy fermented'},

    // ════════ SOY / TOFU ════════
    {name:'Tofu (firm, raw)', serving:100, cal:144, p:17, c:2.8, f:8.7,
     servings:[{n:'¼ block',g:80},{n:'½ block',g:150},{n:'1 block',g:300}],
     tags:'soy tofu tauhu vegan protein'},
    {name:'Tofu (silken)', serving:100, cal:55, p:5, c:2, f:2.7,
     servings:[{n:'¼ block',g:80},{n:'½ block',g:150}],
     tags:'soy soft tofu tauhu'},
    {name:'Tofu (fried, tauhu goreng)', serving:100, cal:190, p:12, c:3.5, f:14,
     servings:[{n:'1 piece',g:50},{n:'2 pieces',g:100},{n:'3 pieces',g:150}],
     tags:'fried tofu tauhu goreng'},
    {name:'Tofu Puff / Tofu Pok', serving:80, cal:230, p:14, c:4, f:18,
     servings:[{n:'2 pieces',g:40},{n:'4 pieces',g:80}],
     tags:'tofu puff tauhu pok fried'},
    {name:'Tempeh (fermented soybean)', serving:100, cal:193, p:19, c:9, f:11,
     servings:[{n:'½ block',g:80},{n:'1 block',g:150}],
     tags:'tempeh soy vegan protein fermented'},
    {name:'Soy Milk (unsweetened)', serving:250, cal:33, p:3, c:2.4, f:1.5,
     servings:[{n:'1 glass (250ml)',g:250},{n:'1 large glass (350ml)',g:350}],
     tags:'soy milk vegan dairy'},
    {name:'Edamame (cooked, shelled)', serving:100, cal:122, p:11, c:10, f:5,
     servings:[{n:'½ cup',g:80},{n:'1 cup',g:155}],
     tags:'edamame soy vegan protein'},

    // ════════ GRAINS / BREAD / RICE (staples) ════════
    {name:'Steamed White Rice (nasi putih, 1 bowl)', serving:180, cal:130, p:2.7, c:28, f:0.3,
     servings:[{n:'½ bowl',g:90},{n:'1 bowl',g:180},{n:'1 large bowl',g:270},{n:'1 plate',g:350}],
     tags:'plain rice nasi white cooked boiled putih steamed'},
    {name:'Steamed Brown Rice', serving:180, cal:122, p:2.6, c:25, f:1,
     servings:[{n:'½ bowl',g:90},{n:'1 bowl',g:180},{n:'1 large bowl',g:270}],
     tags:'brown rice wholegrain healthy'},
    {name:'Fried Rice (nasi goreng biasa)', serving:300, cal:163, p:5, c:24, f:5,
     servings:[{n:'1 plate (small)',g:250},{n:'1 plate',g:350},{n:'1 large plate',g:450}],
     tags:'fried rice goreng nasi'},
    {name:'White Bread (per slice)', serving:32, cal:255, p:8, c:47, f:3.5,
     servings:[{n:'1 slice',g:32},{n:'2 slices',g:64},{n:'3 slices',g:96}],
     tags:'bread white toast roti slice sliced white bread'},
    {name:'Wholemeal Bread (per slice)', serving:32, cal:238, p:9, c:43, f:3,
     servings:[{n:'1 slice',g:32},{n:'2 slices',g:64}],
     tags:'bread wholemeal wholegrain slice sliced'},
    {name:'White Rice (raw / uncooked)', serving:50, cal:365, p:7, c:80, f:0.7,
     servings:[{n:'¼ cup dry',g:45},{n:'½ cup dry',g:90}],
     tags:'raw uncooked rice'},
    {name:'Oats (instant, dry)', serving:40, cal:374, p:13, c:66, f:7,
     servings:[{n:'½ cup',g:40},{n:'1 cup',g:80}],
     tags:'oats breakfast cereal oatmeal quaker'},
    {name:'Oats (cooked, with water)', serving:240, cal:71, p:2.5, c:12, f:1.4,
     servings:[{n:'1 small bowl',g:200},{n:'1 bowl',g:280}],
     tags:'oats porridge oatmeal cooked breakfast'},
    {name:'Mee / Yellow Noodles (cooked)', serving:150, cal:130, p:4, c:27, f:0.5,
     servings:[{n:'½ plate',g:100},{n:'1 plate',g:200}],
     tags:'yellow noodle mee kuning'},
    {name:'Kuey Teow / Flat Rice Noodles (cooked)', serving:200, cal:108, p:3, c:24, f:0.3,
     servings:[{n:'1 portion',g:200},{n:'1 large portion',g:300}],
     tags:'flat noodle rice noodle kway teow'},
    {name:'Vermicelli / Bihun (cooked)', serving:150, cal:109, p:2, c:25, f:0.2,
     servings:[{n:'1 portion',g:150},{n:'1 large portion',g:220}],
     tags:'bihun vermicelli rice noodle'},
    {name:'Glass Noodles / Mee Suah (cooked)', serving:150, cal:96, p:2, c:22, f:0.1,
     servings:[{n:'1 portion',g:150},{n:'1 large portion',g:220}],
     tags:'glass noodles mee suah transparent'},
    {name:'Instant Noodles (cooked, plain)', serving:80, cal:370, p:9, c:54, f:13,
     servings:[{n:'1 pack (cooked)',g:300},{n:'1 pack dry only',g:80}],
     tags:'instant noodle mee maggi indomie'},
    {name:'Roti / Flatbread', serving:60, cal:280, p:8, c:48, f:5,
     servings:[{n:'1 small',g:50},{n:'1 piece',g:80}],
     tags:'bread roti flatbread'},

    // ════════ FRUITS — tropical focus ════════
    {name:'Banana (pisang)', serving:120, cal:89, p:1.1, c:23, f:0.3,
     servings:[{n:'1 small (pisang emas)',g:80},{n:'1 medium',g:120},{n:'1 large',g:150}],
     tags:'fruit pisang banana'},
    {name:'Apple', serving:180, cal:52, p:0.3, c:14, f:0.2,
     servings:[{n:'1 small',g:150},{n:'1 medium',g:180},{n:'1 large',g:220}],
     tags:'fruit apple'},
    {name:'Orange', serving:130, cal:47, p:0.9, c:12, f:0.1,
     servings:[{n:'1 small',g:100},{n:'1 medium',g:130},{n:'1 large',g:180}],
     tags:'fruit orange limau'},
    {name:'Mango (harum manis / mangga)', serving:165, cal:60, p:0.8, c:15, f:0.4,
     servings:[{n:'½ mango',g:100},{n:'1 mango',g:200}],
     tags:'fruit mango mangga tropical'},
    {name:'Papaya (betik)', serving:140, cal:43, p:0.5, c:11, f:0.3,
     servings:[{n:'1 slice',g:100},{n:'1 large slice',g:150},{n:'1 bowl',g:200}],
     tags:'fruit papaya betik tropical'},
    {name:'Watermelon (tembikai)', serving:280, cal:30, p:0.6, c:8, f:0.2,
     servings:[{n:'1 slice (thin)',g:200},{n:'1 slice',g:300},{n:'1 large slice',g:400}],
     tags:'fruit watermelon tembikai tropical'},
    {name:'Pineapple (nanas)', serving:165, cal:50, p:0.5, c:13, f:0.1,
     servings:[{n:'2 rings',g:100},{n:'½ cup chunks',g:165},{n:'1 cup chunks',g:250}],
     tags:'fruit pineapple nanas tropical'},
    {name:'Durian (flesh)', serving:100, cal:147, p:1.5, c:27, f:5.3,
     servings:[{n:'1 seed (small)',g:40},{n:'1 seed (medium)',g:70},{n:'1 seed (large)',g:100}],
     tags:'fruit durian tropical'},
    {name:'Guava (jambu batu)', serving:150, cal:68, p:2.6, c:14, f:1,
     servings:[{n:'1 small guava',g:100},{n:'1 guava',g:170}],
     tags:'fruit guava jambu tropical'},
    {name:'Rambutan', serving:50, cal:68, p:0.9, c:16, f:0.2,
     servings:[{n:'3 fruits',g:50},{n:'5 fruits',g:80},{n:'10 fruits',g:150}],
     tags:'fruit rambutan tropical'},
    {name:'Jackfruit / Nangka (flesh)', serving:100, cal:95, p:1.7, c:23, f:0.6,
     servings:[{n:'1 small piece',g:80},{n:'2 pieces',g:150}],
     tags:'fruit jackfruit nangka tropical'},
    {name:'Dragon Fruit (pitaya, red)', serving:200, cal:60, p:1.2, c:13, f:0.4,
     servings:[{n:'½ fruit',g:200},{n:'1 whole fruit',g:350}],
     tags:'fruit dragon fruit pitaya tropical'},
    {name:'Mangosteen', serving:100, cal:73, p:0.4, c:18, f:0.6,
     servings:[{n:'2 fruits',g:80},{n:'4 fruits',g:160}],
     tags:'fruit mangosteen tropical'},
    {name:'Starfruit (belimbing)', serving:130, cal:31, p:1, c:7, f:0.3,
     servings:[{n:'1 fruit',g:130}],
     tags:'fruit starfruit belimbing tropical'},
    {name:'Longan', serving:100, cal:60, p:1.3, c:15, f:0.1,
     servings:[{n:'10 fruits',g:100},{n:'20 fruits',g:200}],
     tags:'fruit longan tropical'},
    {name:'Grape', serving:150, cal:69, p:0.7, c:18, f:0.2,
     servings:[{n:'small bunch',g:100},{n:'medium bunch',g:150}],
     tags:'fruit grape anggur'},
    {name:'Strawberry', serving:150, cal:32, p:0.7, c:8, f:0.3,
     servings:[{n:'5 berries',g:80},{n:'10 berries',g:150},{n:'1 cup',g:152}],
     tags:'fruit strawberry'},

    // ════════ VEGETABLES — Malaysian focus ════════
    {name:'Kangkung / Water Spinach (cooked)', serving:100, cal:19, p:2.6, c:3.1, f:0.2,
     servings:[{n:'1 side dish',g:100},{n:'1 large side',g:150}],
     tags:'vegetable kangkung water spinach sayur malay'},
    {name:'Bayam / Spinach (cooked)', serving:100, cal:23, p:2.9, c:3.6, f:0.4,
     servings:[{n:'1 side dish',g:100},{n:'1 large side',g:150}],
     tags:'vegetable bayam spinach sayur'},
    {name:'Kailan / Chinese Broccoli (cooked)', serving:100, cal:35, p:2, c:6, f:0.7,
     servings:[{n:'1 side dish',g:100},{n:'1 large side',g:150}],
     tags:'vegetable kailan chinese broccoli sayur'},
    {name:'Broccoli (cooked)', serving:100, cal:35, p:2.4, c:7, f:0.4,
     servings:[{n:'½ cup',g:80},{n:'1 cup',g:156}],
     tags:'vegetable broccoli'},
    {name:'Ladies Finger / Okra / Bendi (cooked)', serving:100, cal:33, p:2, c:7, f:0.2,
     servings:[{n:'5 pieces',g:80},{n:'8 pieces',g:130}],
     tags:'vegetable okra ladies finger bendi sayur'},
    {name:'Long Bean / Kacang Panjang (cooked)', serving:100, cal:47, p:2.8, c:8, f:0.4,
     servings:[{n:'1 small serving',g:80},{n:'1 serving',g:120}],
     tags:'vegetable long bean kacang panjang sayur'},
    {name:'Petai / Bitter Bean', serving:50, cal:142, p:8, c:24, f:2,
     servings:[{n:'10 beans',g:30},{n:'20 beans',g:60}],
     tags:'petai bitter bean vegetable malay'},
    {name:'Beansprout / Taugeh', serving:100, cal:30, p:3.1, c:5.9, f:0.2,
     servings:[{n:'½ cup',g:50},{n:'1 cup',g:100}],
     tags:'beansprout taugeh vegetable'},
    {name:'Carrot (cooked)', serving:100, cal:41, p:0.9, c:10, f:0.2,
     servings:[{n:'1 medium carrot',g:80},{n:'1 large carrot',g:120}],
     tags:'vegetable carrot wortel'},
    {name:'Cabbage (cooked)', serving:100, cal:25, p:1.3, c:5.8, f:0.1,
     servings:[{n:'½ cup',g:80},{n:'1 cup',g:150}],
     tags:'vegetable cabbage kobis'},
    {name:'Cucumber (raw)', serving:100, cal:16, p:0.7, c:3.6, f:0.1,
     servings:[{n:'½ cucumber',g:150},{n:'5 slices',g:50}],
     tags:'vegetable cucumber timun raw'},
    {name:'Tomato (raw)', serving:120, cal:18, p:0.9, c:3.9, f:0.2,
     servings:[{n:'1 small tomato',g:80},{n:'1 tomato',g:130}],
     tags:'vegetable tomato tomat'},
    {name:'Yam / Keladi (cooked)', serving:100, cal:118, p:1.5, c:28, f:0.1,
     servings:[{n:'1 small piece',g:80},{n:'1 piece',g:120}],
     tags:'yam keladi root vegetable taro'},
    {name:'Tapioca / Ubi Kayu (boiled)', serving:100, cal:160, p:1.4, c:38, f:0.3,
     servings:[{n:'1 small piece',g:80},{n:'1 piece',g:120}],
     tags:'tapioca ubi kayu root vegetable cassava'},
    {name:'Sweet Potato / Ubi Keledek (boiled)', serving:130, cal:86, p:1.6, c:20, f:0.1,
     servings:[{n:'1 small',g:100},{n:'1 medium',g:130},{n:'1 large',g:180}],
     tags:'sweet potato ubi keledek'},

    // ════════ LEGUMES / NUTS ════════
    {name:'Chickpeas / Kacang Kuda (cooked)', serving:164, cal:164, p:9, c:27, f:2.6,
     servings:[{n:'½ cup',g:80},{n:'1 cup',g:164}],
     tags:'legume chickpeas kacang protein'},
    {name:'Lentils / Dal (cooked)', serving:198, cal:116, p:9, c:20, f:0.4,
     servings:[{n:'½ cup',g:100},{n:'1 cup',g:198}],
     tags:'legume lentil dal dhal protein vegan'},
    {name:'Peanuts / Kacang Tanah (roasted)', serving:30, cal:567, p:26, c:16, f:49,
     servings:[{n:'small handful',g:20},{n:'handful',g:30},{n:'large handful',g:45}],
     tags:'nuts peanut kacang tanah'},
    {name:'Peanut Butter (smooth)', serving:32, cal:598, p:22, c:20, f:51,
     servings:[{n:'1 tsp',g:7},{n:'1 tbsp',g:16},{n:'2 tbsp',g:32}],
     tags:'peanut butter kacang spread protein'},
    {name:'Almond (raw)', serving:30, cal:579, p:21, c:22, f:50,
     servings:[{n:'10 almonds',g:14},{n:'20 almonds',g:28},{n:'small handful',g:30}],
     tags:'nuts almond badam protein'},
    {name:'Cashew (roasted)', serving:30, cal:553, p:15, c:33, f:44,
     servings:[{n:'10 cashews',g:15},{n:'small handful',g:28}],
     tags:'nuts cashew gajus'},
    {name:'Black Bean (cooked)', serving:172, cal:132, p:9, c:24, f:0.5,
     servings:[{n:'½ cup',g:90},{n:'1 cup',g:172}],
     tags:'legume black bean kacang hitam'},

    // ════════ OILS / FATS ════════
    {name:'Cooking Oil (vegetable / palm)', serving:14, cal:884, p:0, c:0, f:100,
     servings:[{n:'1 tsp',g:4.5},{n:'1 tbsp',g:14}],
     tags:'oil cooking minyak masak'},
    {name:'Olive Oil', serving:14, cal:884, p:0, c:0, f:100,
     servings:[{n:'1 tsp',g:4.5},{n:'1 tbsp',g:14}],
     tags:'oil olive healthy fat'},
    {name:'Coconut Oil / Minyak Kelapa', serving:14, cal:862, p:0, c:0, f:100,
     servings:[{n:'1 tsp',g:4.5},{n:'1 tbsp',g:14}],
     tags:'oil coconut kelapa'},
    {name:'Coconut Milk / Santan (thick)', serving:60, cal:230, p:2.3, c:3.4, f:24,
     servings:[{n:'2 tbsp',g:30},{n:'¼ cup',g:60},{n:'½ cup',g:120}],
     tags:'coconut milk santan cooking'},
    {name:'Kaya (coconut jam)', serving:20, cal:293, p:3, c:55, f:7,
     servings:[{n:'1 tsp',g:7},{n:'1 tbsp',g:20},{n:'2 tbsp',g:40}],
     tags:'kaya coconut jam spread bread toast'},

    // ════════ DRINKS — Malaysian focus ════════
    {name:'Water (plain)', serving:250, cal:0, p:0, c:0, f:0,
     servings:[{n:'1 glass (250ml)',g:250},{n:'1 bottle (500ml)',g:500}],
     tags:'water plain drink'},
    {name:'Teh Tarik (with condensed milk)', serving:250, cal:90, p:2, c:15, f:3,
     servings:[{n:'1 small glass',g:200},{n:'1 glass',g:250},{n:'1 large glass',g:350}],
     tags:'teh tarik milk tea mamak drink kopi'},
    {name:'Teh (hot, with condensed milk)', serving:200, cal:90, p:1.5, c:14, f:2.5,
     servings:[{n:'1 cup',g:200},{n:'1 large cup',g:300}],
     tags:'teh tea milk condensed drink'},
    {name:'Teh O Ais (iced black tea + sugar)', serving:250, cal:60, p:0, c:15, f:0,
     servings:[{n:'1 glass',g:250},{n:'1 large glass',g:350}],
     tags:'teh o ais black tea sugar iced drink'},
    {name:'Kopi (with condensed milk)', serving:200, cal:100, p:1.5, c:16, f:3,
     servings:[{n:'1 cup',g:200},{n:'1 large cup',g:300}],
     tags:'kopi coffee condensed milk mamak drink'},
    {name:'Kopi O (black coffee + sugar)', serving:200, cal:30, p:0.2, c:7, f:0,
     servings:[{n:'1 cup',g:200},{n:'1 large cup',g:300}],
     tags:'kopi o black coffee sugar mamak drink'},
    {name:'Cham (coffee + tea + condensed milk)', serving:250, cal:95, p:2.5, c:17, f:2,
     servings:[{n:'1 glass',g:250},{n:'1 large glass',g:350}],
     tags:'cham coffee tea mix mamak drink'},
    {name:'Iced Milo (with condensed milk)', serving:350, cal:120, p:3, c:22, f:3,
     servings:[{n:'1 glass (small)',g:250},{n:'1 glass',g:350}],
     tags:'milo iced chocolate drink mamak'},
    {name:'Milo (hot, with powder + condensed milk)', serving:250, cal:130, p:3.5, c:23, f:3.5,
     servings:[{n:'1 mug',g:250},{n:'1 large mug',g:300}],
     tags:'milo hot chocolate nestle drink'},
    {name:'Coconut Water / Air Kelapa Muda (fresh)', serving:350, cal:19, p:0.7, c:4, f:0.2,
     servings:[{n:'1 small coconut',g:250},{n:'1 coconut',g:350}],
     tags:'coconut water kelapa muda fresh drink low cal'},
    {name:'Air Tebu / Sugarcane Juice', serving:300, cal:66, p:0, c:16, f:0,
     servings:[{n:'1 glass (small)',g:250},{n:'1 glass',g:350}],
     tags:'sugarcane juice air tebu drink hawker'},
    {name:'Bandung (rose syrup + evaporated milk)', serving:250, cal:95, p:2, c:20, f:1.5,
     servings:[{n:'1 glass',g:250},{n:'1 large glass',g:350}],
     tags:'bandung rose syrup milk drink pink'},
    {name:'Sirap Ais (rose syrup + water)', serving:250, cal:80, p:0, c:20, f:0,
     servings:[{n:'1 glass',g:250}],
     tags:'sirap ais rose syrup drink sweet red'},
    {name:'Barley Water (sweetened)', serving:250, cal:55, p:0.5, c:13, f:0.2,
     servings:[{n:'1 glass',g:250},{n:'1 large glass',g:350}],
     tags:'barley water drink sweetened'},
    {name:'Chrysanthemum Tea (sweetened)', serving:250, cal:45, p:0, c:11, f:0,
     servings:[{n:'1 can (300ml)',g:300},{n:'1 glass',g:250}],
     tags:'chrysanthemum tea drink chinese'},
    {name:'Soy Milk (sweetened, hawker-style)', serving:250, cal:63, p:3.5, c:10, f:1.5,
     servings:[{n:'1 glass (small)',g:200},{n:'1 glass',g:250}],
     tags:'soy milk susu kacang sweetened drink'},
    {name:'Air Limau / Lime Juice (sweetened)', serving:250, cal:40, p:0.2, c:10, f:0.1,
     servings:[{n:'1 glass',g:250}],
     tags:'lime juice air limau drink'},
    {name:'Orange Juice (fresh)', serving:250, cal:45, p:0.7, c:10, f:0.2,
     servings:[{n:'1 glass',g:250}],
     tags:'orange juice fresh drink'},
    {name:'Coffee (black, no sugar)', serving:240, cal:2, p:0.3, c:0, f:0,
     servings:[{n:'1 cup',g:240}],
     tags:'coffee black no sugar'},
    {name:'Milo (powder)', brand:'Nestle', serving:25, cal:385, p:10.5, c:70, f:6.5,
     servings:[{n:'1 heaped tbsp (20g)',g:20},{n:'2 tbsp (25g)',g:25}],
     tags:'milo chocolate malt drink nestle powder'},
    {name:'Milo RTD Can (240ml)', brand:'Nestle', serving:240, cal:77, p:1.8, c:15, f:1.6,
     servings:[{n:'1 can (240ml)',g:240}],
     tags:'milo ready to drink can nestle'},
    {name:'100Plus Isotonic (500ml)', brand:'100Plus', serving:500, cal:29, p:0, c:7, f:0,
     servings:[{n:'½ bottle (250ml)',g:250},{n:'1 bottle (500ml)',g:500}],
     tags:'100plus isotonic sports drink'},

    // ════════ MALAYSIAN MAINS — Malay ════════
    {name:'Nasi Lemak (sambal, ikan bilis, egg, peanut)', serving:230, cal:200, p:5, c:25, f:9,
     servings:[{n:'1 small packet',g:200},{n:'1 packet',g:280},{n:'1 plate (with extras)',g:400}],
     tags:'malaysian breakfast rice coconut malay nasi lemak'},
    {name:'Nasi Goreng Kampung', serving:300, cal:170, p:5, c:23, f:6,
     servings:[{n:'1 plate (small)',g:250},{n:'1 plate',g:350}],
     tags:'fried rice goreng malay kampung'},
    {name:'Nasi Goreng Cina / Chinese Fried Rice', serving:300, cal:163, p:5, c:24, f:5,
     servings:[{n:'1 plate (small)',g:250},{n:'1 plate',g:350}],
     tags:'fried rice chinese goreng'},
    {name:'Nasi Briyani Ayam', serving:350, cal:190, p:8, c:25, f:7,
     servings:[{n:'1 plate (small)',g:280},{n:'1 plate',g:380}],
     tags:'indian rice biryani ayam chicken'},
    {name:'Nasi Kerabu (blue rice, Kelantanese)', serving:300, cal:160, p:6, c:24, f:4,
     servings:[{n:'1 plate',g:300}],
     tags:'kelantan rice ulam malay nasi kerabu'},
    {name:'Nasi Dagang (Terengganu)', serving:250, cal:200, p:6, c:28, f:8,
     servings:[{n:'1 packet',g:250}],
     tags:'terengganu rice nasi dagang'},
    {name:'Nasi Kandar (rice + mixed curry)', serving:400, cal:185, p:8, c:24, f:6,
     servings:[{n:'1 plate (plain)',g:350},{n:'1 plate (loaded)',g:500}],
     tags:'mamak rice curry nasi kandar penang'},
    {name:'Nasi Campur / Economy Mixed Rice', serving:350, cal:175, p:8, c:22, f:6,
     servings:[{n:'1 plate (1 meat 2 veg)',g:350},{n:'1 plate (1 meat 3 veg)',g:400}],
     tags:'economy mixed rice nasi campur'},
    {name:'Nasi Padang (rice + 3 Malay dishes)', serving:400, cal:165, p:7, c:22, f:6,
     servings:[{n:'1 plate',g:400},{n:'1 large plate',g:550}],
     tags:'nasi padang malay rice mixed curry'},
    {name:'Nasi Tomato (tomato rice)', serving:200, cal:190, p:4, c:35, f:4.5,
     servings:[{n:'1 plate',g:300}],
     tags:'tomato rice nasi tomato malay'},
    {name:'Hainanese Chicken Rice (rice only)', serving:200, cal:180, p:3, c:38, f:3,
     servings:[{n:'1 bowl rice only',g:200},{n:'1 large bowl',g:280}],
     tags:'chicken rice hainanese nasi ayam'},
    {name:'Chicken Rice (full plate: rice + chicken)', serving:350, cal:173, p:14, c:21, f:6,
     servings:[{n:'1 plate (small)',g:280},{n:'1 plate',g:380}],
     tags:'nasi ayam chicken rice hainanese'},
    {name:'Lontong (with sayur lodeh)', serving:350, cal:115, p:4, c:18, f:3,
     servings:[{n:'1 plate',g:350}],
     tags:'lontong sayur lodeh malay rice cake'},
    {name:'Ketupat / Nasi Impit', serving:100, cal:120, p:2, c:27, f:0.2,
     servings:[{n:'2 small cubes',g:80},{n:'3 cubes',g:120}],
     tags:'ketupat nasi impit rice cake compressed'},
    {name:'Lemang (glutinous rice in bamboo)', serving:100, cal:210, p:4, c:40, f:4.5,
     servings:[{n:'1 small piece',g:80},{n:'1 piece',g:120}],
     tags:'lemang glutinous rice bambu bamboo festive'},

    // ════════ MALAYSIAN MAINS — Noodles ════════
    {name:'Char Kuey Teow (Penang-style)', serving:280, cal:192, p:8, c:22, f:8,
     servings:[{n:'1 plate (small)',g:230},{n:'1 plate',g:320}],
     tags:'penang fried flat noodle ckt char kuey teow'},
    {name:'Hokkien Mee (KL dark)', serving:350, cal:158, p:7, c:18, f:6,
     servings:[{n:'1 plate (small)',g:280},{n:'1 plate',g:380}],
     tags:'fried noodle hokkien mee kl'},
    {name:'Wantan Mee / Wonton Noodles (dry)', serving:300, cal:165, p:8, c:24, f:4,
     servings:[{n:'1 plate',g:300}],
     tags:'noodle char siew wantan wonton mee dry'},
    {name:'Curry Mee / Curry Laksa', serving:450, cal:120, p:5, c:12, f:6,
     servings:[{n:'1 bowl (small)',g:380},{n:'1 bowl',g:500}],
     tags:'noodle curry soup laksa mee'},
    {name:'Asam Laksa (Penang)', serving:450, cal:90, p:5, c:14, f:1.5,
     servings:[{n:'1 bowl (small)',g:380},{n:'1 bowl',g:500}],
     tags:'penang sour fish noodle asam laksa'},
    {name:'Mee Goreng Mamak', serving:300, cal:180, p:6, c:26, f:6,
     servings:[{n:'1 plate (small)',g:250},{n:'1 plate',g:350}],
     tags:'fried noodle mamak mee goreng'},
    {name:'Maggi Goreng', serving:280, cal:200, p:6, c:26, f:8,
     servings:[{n:'1 plate',g:280}],
     tags:'fried instant noodle mamak maggi goreng'},
    {name:'Mee Rebus (Johor-style)', serving:400, cal:110, p:4, c:17, f:3,
     servings:[{n:'1 bowl',g:400}],
     tags:'noodle gravy mee rebus johor'},
    {name:'Mee Soto (chicken noodle soup)', serving:400, cal:85, p:5, c:11, f:2,
     servings:[{n:'1 bowl',g:400}],
     tags:'noodle soup chicken mee soto'},
    {name:'Bihun Sup / Rice Vermicelli Soup', serving:400, cal:70, p:4, c:10, f:1.5,
     servings:[{n:'1 bowl',g:400}],
     tags:'bihun vermicelli soup'},
    {name:'Kuey Teow Soup', serving:450, cal:65, p:4, c:9, f:1.5,
     servings:[{n:'1 bowl',g:450}],
     tags:'kuey teow noodle soup'},
    {name:'Soto Ayam (chicken soup with noodle)', serving:400, cal:80, p:6, c:9, f:2,
     servings:[{n:'1 bowl (small)',g:350},{n:'1 bowl',g:450}],
     tags:'soto ayam chicken soup noodle malay'},

    // ════════ MALAYSIAN MAINS — Chinese hawker ════════
    {name:'Bak Kut Teh (pork rib herbal soup)', serving:400, cal:120, p:12, c:2, f:7,
     servings:[{n:'1 bowl',g:400}],
     tags:'pork herbal soup bak kut teh chinese'},
    {name:'Bak Chor Mee (dry, with minced pork)', serving:300, cal:165, p:9, c:22, f:5,
     servings:[{n:'1 plate',g:300}],
     tags:'bak chor mee minced pork noodle chinese dry'},
    {name:'Duck Noodles (bebek mee)', serving:350, cal:150, p:9, c:20, f:4,
     servings:[{n:'1 plate',g:350}],
     tags:'duck noodle bebek chinese hawker'},
    {name:'Wonton Soup (noodles + dumplings)', serving:400, cal:120, p:8, c:18, f:2,
     servings:[{n:'1 bowl',g:400}],
     tags:'wonton soup noodle chinese'},
    {name:'Prawn Mee / Har Mee (noodle soup)', serving:450, cal:100, p:7, c:13, f:2,
     servings:[{n:'1 bowl',g:450}],
     tags:'prawn mee noodle soup hokkien'},
    {name:'Claypot Chicken Rice', serving:350, cal:185, p:10, c:25, f:5,
     servings:[{n:'1 clay pot (1 person)',g:350}],
     tags:'claypot rice chicken chinese'},
    {name:'Popiah (fresh spring roll)', serving:120, cal:170, p:6, c:24, f:5,
     servings:[{n:'1 popiah',g:120},{n:'2 popiah',g:240}],
     tags:'popiah spring roll fresh chinese'},
    {name:'Spring Roll (fried, lumpia goreng)', serving:80, cal:230, p:5, c:24, f:13,
     servings:[{n:'1 small spring roll',g:60},{n:'1 spring roll',g:90}],
     tags:'fried spring roll lumpia goreng chinese'},
    {name:'Yong Tau Foo (5 pcs, soup)', serving:250, cal:90, p:7, c:6, f:4,
     servings:[{n:'5 pieces (soup)',g:250},{n:'8 pieces',g:400}],
     tags:'yong tau foo soup stuffed tofu chinese'},
    {name:'Chee Cheong Fun (plain, with sauce)', serving:200, cal:120, p:3, c:22, f:2,
     servings:[{n:'1 plate (3 rolls)',g:200},{n:'1 large plate (5 rolls)',g:300}],
     tags:'chee cheong fun rice roll chinese dim sum'},
    {name:'Tau Foo Fah / Douhua (soybean pudding)', serving:300, cal:53, p:3, c:6, f:1.5,
     servings:[{n:'1 bowl',g:300}],
     tags:'tau foo fah douhua soy pudding dessert chinese'},
    {name:'Tom Yum Soup (seafood)', serving:300, cal:60, p:5, c:5, f:2.5,
     servings:[{n:'1 bowl',g:300}],
     tags:'tom yum soup thai seafood'},
    {name:'Braised Pork Belly / Tau Yew Bak', serving:100, cal:280, p:14, c:3, f:24,
     servings:[{n:'2 slices',g:80},{n:'3 slices',g:120}],
     tags:'braised pork belly tau yew bak chinese'},
    {name:'Steamed Fish (with ginger & soy)', serving:200, cal:115, p:18, c:2, f:3.5,
     servings:[{n:'1 small fillet',g:150},{n:'1 fillet',g:220}],
     tags:'steamed fish chinese ginger soy'},
    {name:'Sweet & Sour Pork (ku lo yuk)', serving:150, cal:200, p:11, c:18, f:9,
     servings:[{n:'1 small portion',g:120},{n:'1 portion',g:180}],
     tags:'sweet sour pork ku lo yuk chinese'},
    {name:'Prawn Paste Chicken / Har Cheong Gai', serving:120, cal:250, p:20, c:6, f:16,
     servings:[{n:'1 piece (small)',g:100},{n:'1 piece',g:140}],
     tags:'har cheong gai prawn paste chicken fried chinese'},

    // ════════ MALAYSIAN MAINS — Dim Sum ════════
    {name:'Har Gow (shrimp dumpling, 3 pcs)', serving:50, cal:170, p:9, c:20, f:5,
     servings:[{n:'3 pieces',g:50},{n:'6 pieces',g:100}],
     tags:'har gow shrimp dumpling dim sum chinese'},
    {name:'Siu Mai (pork & shrimp, 3 pcs)', serving:60, cal:220, p:13, c:12, f:13,
     servings:[{n:'3 pieces',g:60},{n:'6 pieces',g:120}],
     tags:'siu mai pork shrimp dumpling dim sum chinese'},
    {name:'Char Siu Bao (steamed BBQ pork bun)', serving:80, cal:250, p:9, c:37, f:7,
     servings:[{n:'1 bun',g:80},{n:'2 buns',g:160}],
     tags:'char siu bao steamed bun bbq pork dim sum'},
    {name:'Char Siu Bao (baked, cocktail bun)', serving:80, cal:330, p:9, c:43, f:13,
     servings:[{n:'1 bun',g:80},{n:'2 buns',g:160}],
     tags:'char siu bao baked bun bbq pork chinese'},
    {name:'Lo Bak Go / Carrot Cake (fried, 2 pcs)', serving:90, cal:150, p:2, c:18, f:7,
     servings:[{n:'2 slices',g:90},{n:'3 slices',g:135}],
     tags:'lo bak go carrot cake chai tow kway fried dim sum'},
    {name:'Loh Mai Gai (glutinous rice in lotus leaf)', serving:200, cal:220, p:7, c:33, f:7,
     servings:[{n:'1 parcel',g:200}],
     tags:'loh mai gai glutinous rice chicken dim sum'},
    {name:'Egg Tart (Portuguese / HK)', serving:80, cal:280, p:6, c:32, f:14,
     servings:[{n:'1 tart',g:80},{n:'2 tarts',g:160}],
     tags:'egg tart custard tart dim sum portuguese'},
    {name:'Congee / Bubur (plain)', serving:400, cal:40, p:1, c:9, f:0.2,
     servings:[{n:'1 small bowl',g:300},{n:'1 bowl',g:450}],
     tags:'congee porridge plain bubur chinese'},
    {name:'Congee with Chicken (bubur ayam)', serving:400, cal:65, p:6, c:9, f:1,
     servings:[{n:'1 bowl',g:400}],
     tags:'congee porridge chicken bubur ayam'},

    // ════════ MALAYSIAN MAINS — Indian ════════
    {name:'Roti Canai (plain)', serving:80, cal:301, p:7, c:41, f:13,
     servings:[{n:'1 piece',g:80},{n:'1 large piece',g:110},{n:'2 pieces',g:160}],
     tags:'mamak bread flatbread roti canai indian'},
    {name:'Roti Telur (egg roti)', serving:120, cal:290, p:9, c:36, f:13,
     servings:[{n:'1 piece',g:120}],
     tags:'mamak bread egg roti telur indian'},
    {name:'Roti Tisu (thin crispy)', serving:80, cal:380, p:6, c:55, f:15,
     servings:[{n:'1 piece',g:80}],
     tags:'mamak bread roti tisu sweet crispy'},
    {name:'Thosai / Tosai (plain)', serving:100, cal:165, p:4, c:30, f:3,
     servings:[{n:'1 piece (small)',g:70},{n:'1 piece',g:100}],
     tags:'indian dosa thosai tosai'},
    {name:'Appam (rice pancake with coconut milk)', serving:70, cal:200, p:4, c:40, f:2.5,
     servings:[{n:'1 appam',g:70},{n:'2 appam',g:140}],
     tags:'appam indian rice pancake coconut'},
    {name:'Idli (steamed rice cake)', serving:80, cal:132, p:4, c:26, f:0.4,
     servings:[{n:'1 idli',g:40},{n:'2 idli',g:80},{n:'3 idli',g:120}],
     tags:'idli indian steamed rice cake'},
    {name:'Chapati', serving:50, cal:297, p:11, c:46, f:7,
     servings:[{n:'1 piece',g:50},{n:'2 pieces',g:100}],
     tags:'indian flatbread chapati'},
    {name:'Naan (plain)', serving:90, cal:310, p:9, c:50, f:8,
     servings:[{n:'1 piece',g:90},{n:'1 large piece',g:130}],
     tags:'indian bread naan'},
    {name:'Murtabak (stuffed flatbread)', serving:150, cal:250, p:11, c:25, f:12,
     servings:[{n:'1 piece',g:150},{n:'1 large piece',g:220}],
     tags:'mamak stuffed bread murtabak'},
    {name:'Puri (deep-fried bread)', serving:30, cal:350, p:7, c:48, f:15,
     servings:[{n:'1 puri',g:30},{n:'2 puri',g:60}],
     tags:'puri indian fried bread'},
    {name:'Banana Leaf Rice (full meal)', serving:450, cal:145, p:5, c:22, f:4,
     servings:[{n:'1 banana leaf meal',g:450}],
     tags:'banana leaf rice indian meal full'},
    {name:'Mutton Briyani', serving:350, cal:185, p:10, c:24, f:6,
     servings:[{n:'1 plate',g:350}],
     tags:'mutton biryani indian briyani'},
    {name:'Mutton Curry (kari kambing)', serving:150, cal:215, p:17, c:4, f:15,
     servings:[{n:'1 small ladle',g:100},{n:'1 ladle',g:150}],
     tags:'mutton curry kari kambing indian'},
    {name:'Fish Head Curry', serving:200, cal:145, p:14, c:5, f:8,
     servings:[{n:'1 portion',g:200}],
     tags:'fish head curry indian kari ikan'},
    {name:'Dhal Curry (lentil curry)', serving:150, cal:116, p:9, c:20, f:0.4,
     servings:[{n:'1 small ladle',g:100},{n:'1 ladle',g:150}],
     tags:'dhal lentil curry indian dal'},
    {name:'Rasam (pepper soup)', serving:200, cal:25, p:1, c:5, f:0.3,
     servings:[{n:'1 cup',g:200}],
     tags:'rasam pepper soup indian thin curry'},
    {name:'Papadum (fried, 1 piece)', serving:10, cal:450, p:20, c:58, f:15,
     servings:[{n:'1 papadum',g:10},{n:'2 papadum',g:20}],
     tags:'papadum pappadam fried crispy indian snack'},
    {name:'Masala Chai / Teh Masala', serving:200, cal:50, p:2, c:8, f:1.5,
     servings:[{n:'1 cup',g:200}],
     tags:'masala chai teh masala indian spiced tea'},
    {name:'Tandoori Chicken', serving:150, cal:215, p:27, c:2, f:11,
     servings:[{n:'1 drumstick',g:120},{n:'1 quarter chicken',g:200}],
     tags:'tandoori chicken indian grilled'},

    // ════════ MALAY MEAT DISHES ════════
    {name:'Beef Rendang', serving:120, cal:200, p:15, c:6, f:13,
     servings:[{n:'1 small ladle',g:80},{n:'1 ladle',g:120}],
     tags:'malaysian rendang beef daging malay'},
    {name:'Ayam Goreng (Malay fried chicken)', serving:120, cal:248, p:22, c:8, f:14,
     servings:[{n:'1 piece (small)',g:100},{n:'1 piece',g:140}],
     tags:'fried chicken ayam goreng malay'},
    {name:'Ayam Percik (grilled with coconut sauce)', serving:150, cal:200, p:18, c:6, f:12,
     servings:[{n:'1 piece',g:150}],
     tags:'ayam percik grilled chicken coconut malay'},
    {name:'Ayam Masak Merah (tomato chicken)', serving:150, cal:170, p:16, c:7, f:9,
     servings:[{n:'1 piece',g:150}],
     tags:'ayam masak merah tomato chicken malay'},
    {name:'Curry Chicken / Kari Ayam', serving:150, cal:160, p:14, c:5, f:9,
     servings:[{n:'1 small portion',g:100},{n:'1 portion',g:180}],
     tags:'curry chicken kari ayam malay'},
    {name:'Gulai Ikan (Malay fish curry)', serving:200, cal:130, p:14, c:4, f:6,
     servings:[{n:'1 portion',g:200}],
     tags:'gulai ikan fish curry malay'},
    {name:'Asam Pedas (sour spicy fish)', serving:150, cal:100, p:12, c:4, f:4,
     servings:[{n:'1 portion',g:150}],
     tags:'asam pedas sour spicy fish malay'},
    {name:'Satay Chicken (5 sticks, no sauce)', serving:60, cal:225, p:28, c:3, f:11,
     servings:[{n:'5 sticks',g:60},{n:'10 sticks',g:120}],
     tags:'satay grilled chicken skewer malay'},
    {name:'Satay Peanut Sauce', serving:40, cal:230, p:7, c:18, f:15,
     servings:[{n:'1 small cup',g:40},{n:'1 cup',g:80}],
     tags:'satay peanut sauce kuah kacang malay'},
    {name:'Sambal Sotong / Spicy Squid', serving:120, cal:130, p:14, c:6, f:6,
     servings:[{n:'1 portion',g:120}],
     tags:'spicy squid sambal sotong malay'},
    {name:'Ikan Bakar / Grilled Fish', serving:150, cal:130, p:22, c:1, f:4,
     servings:[{n:'1 small fillet',g:120},{n:'1 fillet',g:180}],
     tags:'grilled fish ikan bakar malay'},
    {name:'Otak-otak (spiced fish cake in leaf)', serving:50, cal:150, p:10, c:6, f:9,
     servings:[{n:'1 piece',g:50},{n:'2 pieces',g:100}],
     tags:'otak-otak fish cake grilled leaf malay'},
    {name:'Char Siew / BBQ Pork', serving:100, cal:240, p:20, c:12, f:12,
     servings:[{n:'2 slices',g:80},{n:'3 slices',g:120}],
     tags:'char siew bbq pork roast chinese'},
    {name:'Roast Duck / Siew Ngap', serving:120, cal:240, p:19, c:0, f:18,
     servings:[{n:'2 slices',g:100},{n:'1 portion',g:150}],
     tags:'roast duck siew ngap chinese'},

    // ════════ MALAY SNACKS / KUIH ════════
    {name:'Pisang Goreng (banana fritter)', serving:100, cal:230, p:2, c:38, f:8,
     servings:[{n:'1 piece (small)',g:60},{n:'1 piece',g:90},{n:'2 pieces',g:170}],
     tags:'pisang goreng banana fritter malay snack'},
    {name:'Cekodok Pisang (banana dumpling)', serving:80, cal:220, p:2, c:36, f:8,
     servings:[{n:'2 pieces',g:80},{n:'3 pieces',g:120}],
     tags:'cekodok pisang banana dumpling malay snack'},
    {name:'Cucur Udang (prawn fritter)', serving:80, cal:230, p:8, c:25, f:11,
     servings:[{n:'2 pieces',g:80},{n:'3 pieces',g:120}],
     tags:'cucur udang prawn fritter malay snack'},
    {name:'Keropok Lekor (fish cracker, Terengganu)', serving:100, cal:280, p:12, c:33, f:11,
     servings:[{n:'5 pieces',g:80},{n:'10 pieces',g:160}],
     tags:'keropok lekor fish cracker terengganu malay snack'},
    {name:'Keropok Keping / Prawn Crackers (fried)', serving:30, cal:500, p:8, c:55, f:28,
     servings:[{n:'small handful',g:20},{n:'1 serving',g:30}],
     tags:'prawn cracker keropok keping fried malay snack'},
    {name:'Muruku (Indian crispy snack)', serving:30, cal:530, p:8, c:60, f:27,
     servings:[{n:'small handful',g:25},{n:'1 serving',g:40}],
     tags:'muruku indian crispy snack diwali'},
    {name:'Curry Puff / Epok-epok', serving:85, cal:240, p:5, c:28, f:12,
     servings:[{n:'1 piece (small)',g:70},{n:'1 piece',g:90}],
     tags:'curry puff epok-epok pastry snack malay'},
    {name:'Apam Balik (thick peanut pancake)', serving:120, cal:280, p:6, c:40, f:11,
     servings:[{n:'½ piece',g:80},{n:'1 piece',g:120}],
     tags:'apam balik peanut pancake malay snack'},
    {name:'Ondeh-ondeh (pandan rice ball)', serving:80, cal:240, p:3, c:40, f:8,
     servings:[{n:'4 pieces',g:80},{n:'6 pieces',g:120}],
     tags:'ondeh-ondeh pandan rice ball gula melaka malay kuih'},
    {name:'Kuih Lapis (layered cake)', serving:80, cal:200, p:3, c:38, f:4.5,
     servings:[{n:'2 slices',g:80},{n:'3 slices',g:120}],
     tags:'kuih lapis layered cake malay kuih'},
    {name:'Kuih Seri Muka (pandan custard)', serving:80, cal:220, p:3, c:40, f:5.5,
     servings:[{n:'1 piece',g:80},{n:'1 large piece',g:120}],
     tags:'kuih seri muka pandan custard malay'},
    {name:'Pulut Kuning / Steamed Glutinous Rice', serving:100, cal:175, p:3, c:38, f:1.5,
     servings:[{n:'1 small piece',g:80},{n:'1 piece',g:120}],
     tags:'pulut kuning glutinous rice yellow malay'},
    {name:'Roti Jala with Curry', serving:150, cal:180, p:6, c:22, f:8,
     servings:[{n:'3 pieces with curry',g:150}],
     tags:'roti jala net bread malay curry'},
    {name:'Bubur Kacang (mung bean porridge)', serving:300, cal:130, p:5, c:25, f:1,
     servings:[{n:'1 bowl',g:300}],
     tags:'bubur kacang mung bean porridge dessert malay'},
    {name:'Ais Kacang / ABC', serving:350, cal:180, p:3, c:38, f:2,
     servings:[{n:'1 bowl',g:350}],
     tags:'ais kacang abc shaved ice dessert malaysia'},
    {name:'Cendol (with gula melaka)', serving:300, cal:200, p:2, c:42, f:4,
     servings:[{n:'1 bowl',g:300}],
     tags:'cendol gula melaka dessert malaysia'},
    {name:'Teh Tarik Kurang Manis (less sweet)', serving:250, cal:60, p:1.5, c:10, f:2,
     servings:[{n:'1 glass',g:250}],
     tags:'teh tarik kurang manis less sweet mamak'},
    {name:'Ulam (fresh herbs & veg side)', serving:100, cal:40, p:3, c:5, f:0.8,
     servings:[{n:'1 small plate',g:100}],
     tags:'ulam fresh herbs raw vegetables malay'},

    // ════════ WESTERN / FAST FOOD ════════
    {name:'Pizza (cheese, 1 slice)', serving:107, cal:266, p:11, c:33, f:10,
     servings:[{n:'1 slice',g:107},{n:'2 slices',g:214}],
     tags:'fast food pizza'},
    {name:'Beef Burger (plain)', serving:150, cal:250, p:13, c:30, f:9,
     servings:[{n:'1 burger',g:150}],
     tags:'fast food burger mcdonald'},
    {name:'Cheeseburger', serving:150, cal:280, p:15, c:28, f:12,
     servings:[{n:'1 burger',g:150}],
     tags:'fast food cheeseburger'},
    {name:'Fried Chicken (KFC original, 1 pc)', serving:120, cal:260, p:19, c:9, f:16,
     servings:[{n:'1 piece',g:120}],
     tags:'fast food kfc fried chicken'},
    {name:'Chicken Nuggets (6 pcs)', serving:96, cal:296, p:15, c:16, f:19,
     servings:[{n:'6 pieces',g:96},{n:'9 pieces',g:144}],
     tags:'fast food chicken nuggets'},
    {name:'Chicken Chop (with sauce)', serving:250, cal:180, p:14, c:10, f:9,
     servings:[{n:'1 plate',g:250}],
     tags:'western chicken chop sauce'},
    {name:'Spaghetti Bolognese', serving:350, cal:150, p:7, c:18, f:5,
     servings:[{n:'1 plate',g:350}],
     tags:'pasta spaghetti bolognese western'},
    {name:'Fish & Chips', serving:250, cal:230, p:12, c:20, f:12,
     servings:[{n:'1 plate',g:250}],
     tags:'fast food fish chips western'},
    {name:'Caesar Salad with Chicken', serving:250, cal:130, p:9, c:5, f:8,
     servings:[{n:'1 bowl',g:250}],
     tags:'salad western caesar chicken'},

    // ════════ SNACKS / SWEETS / BAKERY ════════
    {name:'Dark Chocolate (70%)', serving:30, cal:598, p:7.8, c:46, f:43,
     servings:[{n:'2 squares',g:20},{n:'3 squares',g:30},{n:'half bar',g:50}],
     tags:'snack chocolate dark sweet'},
    {name:'Milk Chocolate', serving:30, cal:535, p:7.6, c:59, f:30,
     servings:[{n:'2 squares',g:20},{n:'3 squares',g:30}],
     tags:'snack chocolate milk sweet'},
    {name:'Potato Chips', serving:30, cal:536, p:7, c:53, f:35,
     servings:[{n:'small handful',g:20},{n:'1 serving',g:30}],
     tags:'snack chips crisps potato'},
    {name:'Digestive Biscuits', serving:30, cal:480, p:7, c:62, f:21,
     servings:[{n:'1 biscuit',g:15},{n:'2 biscuits',g:30},{n:'3 biscuits',g:45}],
     tags:'snack digestive biscuit cookie'},
    {name:'Doughnut (glazed)', serving:60, cal:452, p:5, c:51, f:25,
     servings:[{n:'1 doughnut',g:60}],
     tags:'bakery doughnut donut sweet'},
    {name:'Croissant', serving:60, cal:406, p:8, c:46, f:21,
     servings:[{n:'1 croissant (small)',g:50},{n:'1 croissant',g:70}],
     tags:'bakery croissant pastry'},
    {name:'Chocolate Muffin', serving:90, cal:377, p:6, c:50, f:17,
     servings:[{n:'1 muffin (small)',g:70},{n:'1 muffin',g:100}],
     tags:'bakery muffin chocolate'},
    {name:'Ice Cream (vanilla)', serving:100, cal:207, p:3.5, c:24, f:11,
     servings:[{n:'1 scoop',g:80},{n:'2 scoops',g:160}],
     tags:'dessert ice cream vanilla'},
    {name:'Popcorn (plain)', serving:30, cal:387, p:12, c:78, f:4.5,
     servings:[{n:'1 small cup',g:20},{n:'1 cup',g:35}],
     tags:'snack popcorn'},
    {name:'Energy / Protein Bar', serving:50, cal:350, p:10, c:50, f:12,
     servings:[{n:'1 bar',g:50}],
     tags:'snack supplement protein bar energy'},

    // ════════ MALAYSIAN PACKAGED / BRANDED (from product labels, per 100g) ════════
    {name:"Julie's Choco More", brand:"Julie's", serving:36, cal:497, p:6, c:63, f:25,
     servings:[{n:'1 piece',g:12},{n:'4 pieces',g:48}],
     tags:'biscuit chocolate sandwich julie julies snack'},
    {name:"Julie's Butter Crackers", brand:"Julie's", serving:30, cal:496, p:8, c:62, f:24,
     servings:[{n:'1 cracker',g:8},{n:'4 crackers',g:30},{n:'8 crackers',g:60}],
     tags:'biscuit cracker julie julies snack'},
    {name:"Julie's Love Letters", brand:"Julie's", serving:25, cal:508, p:5, c:65, f:26,
     servings:[{n:'2 rolls',g:20},{n:'5 rolls',g:50}],
     tags:'biscuit roll julie julies'},
    {name:"Julie's Peanut Butter Sandwich", brand:"Julie's", serving:36, cal:503, p:9, c:58, f:26,
     servings:[{n:'1 piece',g:12},{n:'4 pieces',g:48}],
     tags:'biscuit peanut butter julie julies'},
    {name:"Julie's Cheese Crackers", brand:"Julie's", serving:30, cal:487, p:9, c:60, f:23,
     servings:[{n:'4 crackers',g:30},{n:'8 crackers',g:60}],
     tags:'biscuit cracker cheese julie julies'},
    {name:'Hup Seng Cream Crackers', brand:'Hup Seng', serving:25, cal:459, p:9, c:67, f:17,
     servings:[{n:'1 cracker',g:8},{n:'3 crackers',g:25},{n:'6 crackers',g:50}],
     tags:'biscuit cracker snack hup seng'},
    {name:'Oreo (original)', brand:'Oreo', serving:34, cal:471, p:5, c:67, f:21,
     servings:[{n:'1 cookie',g:11},{n:'3 cookies',g:34}],
     tags:'biscuit cookie chocolate snack oreo'},
    {name:'Gardenia Original Classic White Bread', brand:'Gardenia', serving:32, cal:255, p:8, c:47, f:3.5,
     servings:[{n:'1 slice',g:32},{n:'2 slices',g:64}],
     tags:'bread white toast roti gardenia'},
    {name:'Gardenia Butterscotch Bread', brand:'Gardenia', serving:32, cal:310, p:7, c:52, f:9,
     servings:[{n:'1 slice',g:32},{n:'2 slices',g:64}],
     tags:'bread sweet gardenia butterscotch'},
    {name:'Massimo Soft White Bread', brand:'Massimo', serving:32, cal:258, p:8, c:48, f:3.5,
     servings:[{n:'1 slice',g:32},{n:'2 slices',g:64}],
     tags:'bread white toast roti massimo slice sliced soft'},
    {name:'Maggi 2-Minute Noodles Chicken', brand:'Maggi', serving:80, cal:370, p:9, c:54, f:13,
     servings:[{n:'1 pack (dry)',g:80},{n:'1 pack (cooked)',g:300}],
     tags:'maggi instant noodle mee chicken ayam'},
    {name:'Maggi Asam Laksa', brand:'Maggi', serving:80, cal:360, p:8, c:52, f:13,
     servings:[{n:'1 pack (dry)',g:80}],
     tags:'maggi instant noodle asam laksa'},
    {name:'Mamee Monster (original)', brand:'Mamee', serving:25, cal:473, p:8, c:62, f:22,
     servings:[{n:'1 pack',g:25}],
     tags:'mamee snack noodle fried instant'},
    {name:'Indomie Mi Goreng', brand:'Indomie', serving:80, cal:390, p:8, c:56, f:15,
     servings:[{n:'1 pack (dry)',g:80}],
     tags:'indomie instant noodle goreng fried'},
    {name:'Milo (3-in-1 sachet, 33g)', brand:'Nestle', serving:33, cal:384, p:7, c:73, f:6,
     servings:[{n:'1 sachet',g:33}],
     tags:'milo nestle 3in1 instant chocolate drink'},
    {name:'Nescafe 3-in-1 Original (sachet, 20g)', brand:'Nestle', serving:20, cal:419, p:5, c:67, f:14,
     servings:[{n:'1 sachet',g:20}],
     tags:'nescafe 3in1 coffee instant nestle'},
    {name:'Old Town White Coffee 3-in-1 (sachet, 35g)', brand:'Old Town', serving:35, cal:446, p:5, c:70, f:16,
     servings:[{n:'1 sachet',g:35}],
     tags:'oldtown old town white coffee 3in1 ipoh kopi'},
    {name:'Dutch Lady Full Cream Milk', brand:'Dutch Lady', serving:250, cal:66, p:3.3, c:4.7, f:3.6,
     servings:[{n:'1 glass (250ml)',g:250},{n:'1 carton (200ml)',g:200}],
     tags:'milk full cream susu dutch lady'},
    {name:'Dutch Lady Low Fat Milk', brand:'Dutch Lady', serving:250, cal:47, p:3.6, c:4.8, f:1.5,
     servings:[{n:'1 glass (250ml)',g:250}],
     tags:'milk low fat susu dutch lady'},
    {name:'Twisties Chicken (per pack 60g)', brand:'Twisties', serving:60, cal:510, p:5, c:60, f:28,
     servings:[{n:'1 pack',g:60}],
     tags:'twisties chips snack crisps chicken'},
    {name:'Mister Potato Chips Original', brand:'Mister Potato', serving:54, cal:530, p:6, c:54, f:32,
     servings:[{n:'1 pack',g:54}],
     tags:'mister potato chips crisps snack'},
    {name:'Pringles Original', brand:'Pringles', serving:30, cal:521, p:5, c:52, f:32,
     servings:[{n:'10 chips',g:30},{n:'1 tube (110g)',g:110}],
     tags:'pringles chips crisps snack'},
    {name:'Ayam Brand Tuna in Water (185g can)', brand:'Ayam Brand', serving:185, cal:116, p:26, c:0, f:1,
     servings:[{n:'½ can',g:92},{n:'1 can',g:185}],
     tags:'tuna can ayam brand protein'},
    {name:'Ayam Brand Sardines in Tomato Sauce', brand:'Ayam Brand', serving:155, cal:165, p:18, c:2, f:9,
     servings:[{n:'1 can',g:155}],
     tags:'sardine can ayam brand ikan'},
    {name:'Vitagen (per bottle 125ml)', brand:'Vitagen', serving:125, cal:72, p:1.5, c:14, f:0.3,
     servings:[{n:'1 bottle',g:125},{n:'2 bottles',g:250}],
     tags:'vitagen probiotic drink dairy fermented'},
    {name:'Quaker Oats Instant (plain)', brand:'Quaker', serving:40, cal:374, p:13, c:66, f:7,
     servings:[{n:'½ cup (dry)',g:40},{n:'1 cup (dry)',g:80}],
     tags:'oats quaker breakfast cereal'},
    {name:"Kellogg's Corn Flakes", brand:"Kellogg's", serving:30, cal:357, p:8, c:79, f:1,
     servings:[{n:'1 serving (30g)',g:30},{n:'1 large bowl (45g)',g:45}],
     tags:'cereal cornflakes breakfast kelloggs'},
    {name:'Whey Protein Powder (generic, vanilla)', serving:30, cal:120, p:24, c:3, f:2,
     servings:[{n:'1 scoop (30g)',g:30},{n:'2 scoops',g:60}],
     tags:'whey protein supplement powder gym'},
    {name:'Mass Gainer (generic)', serving:150, cal:600, p:30, c:100, f:8,
     servings:[{n:'1 scoop (150g)',g:150}],
     tags:'mass gainer supplement protein gym'},

    // ════════ RICE DISHES — commonly searched variants ════════
    {name:'Cooked White Rice (plain, 1 bowl)', serving:180, cal:130, p:2.7, c:28, f:0.3,
     servings:[{n:'½ bowl',g:90},{n:'1 bowl',g:180},{n:'1 large bowl',g:270},{n:'1 plate',g:350}],
     tags:'cooked white rice plain nasi putih steamed boiled bowl'},
    {name:'Nasi Lemak (full set)', serving:350, cal:230, p:8, c:29, f:9,
     servings:[{n:'1 standard set',g:350},{n:'1 large set',g:500}],
     tags:'nasi lemak coconut rice sambal anchovies peanut egg malay breakfast'},
    {name:'Nasi Lemak — Coconut Rice only', serving:180, cal:170, p:3, c:33, f:3,
     servings:[{n:'1 serving',g:180}],
     tags:'nasi lemak coconut rice santan nasi'},
    {name:'Nasi Dagang', serving:350, cal:178, p:6, c:30, f:4,
     servings:[{n:'1 pack',g:350}],
     tags:'nasi dagang kelantan terengganu coconut rice fish curry'},
    {name:'Nasi Minyak', serving:200, cal:185, p:4, c:33, f:5,
     servings:[{n:'1 bowl',g:200},{n:'1 large bowl',g:300}],
     tags:'nasi minyak ghee rice kenduri malay'},
    {name:'Nasi Biryani (chicken)', serving:400, cal:210, p:10, c:29, f:7,
     servings:[{n:'1 plate',g:400}],
     tags:'biryani briyani nasi chicken rice spiced indian malay'},
    {name:'Economy Rice / Nasi Campur (3 dishes)', serving:400, cal:195, p:9, c:26, f:7,
     servings:[{n:'1 plate (3 lauk)',g:400},{n:'1 plate (4 lauk)',g:500}],
     tags:'economy rice nasi campur mixed rice lauk pauk warung chinese malay'},
    {name:'Claypot Chicken Rice', serving:400, cal:195, p:14, c:28, f:5,
     servings:[{n:'1 claypot (small)',g:350},{n:'1 claypot',g:500}],
     tags:'claypot chicken rice chinese bak choy soy sauce'},

    // ════════ CURRIES — generic & standalone ════════
    {name:'Curry (chicken, mixed with gravy)', serving:200, cal:160, p:14, c:5, f:9,
     servings:[{n:'1 ladle (150g)',g:150},{n:'1 bowl',g:250}],
     tags:'curry chicken kari ayam gravy generic'},
    {name:'Curry (beef, mixed with gravy)', serving:200, cal:175, p:16, c:5, f:10,
     servings:[{n:'1 ladle (150g)',g:150},{n:'1 bowl',g:250}],
     tags:'curry beef kari daging gravy generic'},
    {name:'Curry (fish, mixed with gravy)', serving:200, cal:130, p:14, c:4, f:6,
     servings:[{n:'1 ladle (150g)',g:150},{n:'1 bowl',g:250}],
     tags:'curry fish kari ikan gravy generic'},
    {name:'Curry (vegetable / mixed veg)', serving:150, cal:90, p:3, c:8, f:5,
     servings:[{n:'1 ladle',g:150}],
     tags:'curry vegetable sayur kari mixed veg generic'},

    // ════════ ROTI / BREAD — kopitiam staples ════════
    {name:'Roti Canai (plain / kosong)', serving:120, cal:300, p:6, c:43, f:12,
     servings:[{n:'1 piece',g:120},{n:'2 pieces',g:240}],
     tags:'roti canai kosong plain mamak flatbread indian'},
    {name:'Roti Canai with Dhal', serving:270, cal:235, p:9, c:37, f:7,
     servings:[{n:'1 piece + dhal',g:270}],
     tags:'roti canai dhal lentil mamak indian'},
    {name:'Roti Canai with Curry', serving:300, cal:240, p:9, c:35, f:9,
     servings:[{n:'1 piece + curry',g:300}],
     tags:'roti canai curry kari mamak indian'},
    {name:'Roti Bakar (toast with kaya & butter)', serving:80, cal:300, p:6, c:44, f:12,
     servings:[{n:'2 slices',g:80}],
     tags:'roti bakar kaya butter toast kopitiam bread'},
    {name:'Kaya (coconut jam)', serving:20, cal:260, p:1.8, c:55, f:4,
     servings:[{n:'1 tbsp',g:20},{n:'2 tbsp',g:40}],
     tags:'kaya coconut jam spread toast kopitiam'},
    {name:'Gardenia Original Classic White Bread', brand:'Gardenia', serving:32, cal:265, p:8, c:49, f:4,
     servings:[{n:'1 slice',g:32},{n:'2 slices',g:64}],
     tags:'gardenia bread white slice sliced toast roti'},
    {name:'Massimo Wholemeal Bread', brand:'Massimo', serving:32, cal:245, p:9, c:44, f:3.5,
     servings:[{n:'1 slice',g:32},{n:'2 slices',g:64}],
     tags:'massimo bread wholemeal wholegrain slice sliced'},

    // ════════ NOODLES — more hawker variants ════════
    {name:'Wantan Mee (dry)', serving:350, cal:155, p:8, c:25, f:4,
     servings:[{n:'1 plate',g:350}],
     tags:'wantan mee wonton noodle dry char siu chinese'},
    {name:'Wantan Mee (soup)', serving:400, cal:120, p:7, c:20, f:2.5,
     servings:[{n:'1 bowl',g:400}],
     tags:'wantan mee wonton noodle soup chinese'},
    {name:'Hokkien Mee (KL-style, fried dark)', serving:400, cal:195, p:10, c:28, f:6,
     servings:[{n:'1 plate',g:400}],
     tags:'hokkien mee fried dark soy chinese noodle lard'},
    {name:'Penang Hokkien Mee (prawn soup)', serving:450, cal:115, p:8, c:14, f:3,
     servings:[{n:'1 bowl',g:450}],
     tags:'hokkien mee penang prawn soup chinese noodle har mee'},
    {name:'Bak Chor Mee (minced pork noodle)', serving:350, cal:165, p:10, c:25, f:4,
     servings:[{n:'1 bowl/plate',g:350}],
     tags:'bak chor mee minced pork noodle chinese BCM'},
    {name:'Pan Mee (hand-pulled flat noodle)', serving:400, cal:140, p:9, c:22, f:3,
     servings:[{n:'1 bowl',g:400}],
     tags:'pan mee ban mian flat noodle chinese minced pork'},
    {name:'Asam Laksa (Penang)', serving:450, cal:105, p:6, c:18, f:2,
     servings:[{n:'1 bowl',g:450}],
     tags:'asam laksa penang sour fish noodle tamarind'},
    {name:'Sarawak Laksa', serving:450, cal:130, p:9, c:15, f:4,
     servings:[{n:'1 bowl',g:450}],
     tags:'sarawak laksa borneo prawn shrimp paste bihun'},

    // ════════ SNACKS / KUIH ════════
    {name:'Pisang Goreng (fried banana)', serving:100, cal:210, p:2, c:32, f:9,
     servings:[{n:'1 piece (large)',g:100},{n:'2 pieces',g:180}],
     tags:'pisang goreng fried banana fritter goreng malay snack'},
    {name:'Ubi Goreng / Fried Tapioca', serving:100, cal:230, p:1.5, c:35, f:10,
     servings:[{n:'1 pack',g:100}],
     tags:'ubi goreng fried tapioca cassava snack malay'},
    {name:'Kuih Lapis (layered cake)', serving:80, cal:195, p:2.5, c:38, f:4,
     servings:[{n:'2 pieces',g:80}],
     tags:'kuih lapis layered cake malay nyonya'},
    {name:'Ondeh Ondeh (glutinous rice ball)', serving:80, cal:185, p:2, c:38, f:3,
     servings:[{n:'4 pieces',g:80}],
     tags:'ondeh ondeh glutinous rice ball pandan palm sugar malay'},
    {name:'Karipap / Curry Puff (baked)', serving:60, cal:200, p:4, c:26, f:9,
     servings:[{n:'1 piece',g:60}],
     tags:'karipap curry puff baked pastry malay snack potato'},

    // ════════ DRINKS — hawker / kopitiam ════════
    {name:'Teh Tarik (pulled tea, with milk & sugar)', serving:300, cal:110, p:3, c:20, f:2.5,
     servings:[{n:'1 glass (small)',g:250},{n:'1 glass',g:300}],
     tags:'teh tarik tea pulled milk sugar kopitiam mamak malay'},
    {name:'Teh O (black tea with sugar)', serving:250, cal:45, p:0, c:11, f:0,
     servings:[{n:'1 glass',g:250}],
     tags:'teh o black tea sugar no milk kopitiam'},
    {name:'Teh O Ais (iced black tea)', serving:300, cal:55, p:0, c:14, f:0,
     servings:[{n:'1 glass',g:300}],
     tags:'teh o ais iced black tea sugar cold kopitiam'},
    {name:'Kopi O (black coffee with sugar)', serving:250, cal:40, p:0.5, c:9, f:0.3,
     servings:[{n:'1 cup',g:250}],
     tags:'kopi o black coffee sugar kopitiam'},
    {name:'Kopi (coffee with condensed milk)', serving:250, cal:130, p:3, c:22, f:3.5,
     servings:[{n:'1 cup',g:250}],
     tags:'kopi coffee condensed milk kopitiam white coffee'},
    {name:'Milo Ais (iced Milo)', serving:300, cal:150, p:4, c:28, f:3,
     servings:[{n:'1 glass',g:300}],
     tags:'milo ais iced cold chocolate malt drink nestle'},
    {name:'Barley Water (sweetened)', serving:300, cal:80, p:0.5, c:19, f:0.2,
     servings:[{n:'1 glass',g:300}],
     tags:'barley water sweetened drink cooling chinese'},
    {name:'Soya Bean Milk (sweetened)', serving:300, cal:65, p:3, c:11, f:1.5,
     servings:[{n:'1 glass',g:300}],
     tags:'soya bean soy milk drink sweetened tau foo fah'},
    {name:'Coconut Water (fresh)', serving:330, cal:19, p:0.7, c:4, f:0.2,
     servings:[{n:'1 young coconut',g:330},{n:'1 can (330ml)',g:330}],
     tags:'coconut water fresh kelapa air young hydration'},
    {name:'Sugarcane Juice', serving:300, cal:83, p:0.3, c:21, f:0,
     servings:[{n:'1 glass',g:300}],
     tags:'sugarcane juice tebu air tebu sweet drink'},

    // ════════ CONDIMENTS / SAUCES ════════
    {name:'Sambal (chilli paste, 1 tbsp)', serving:20, cal:50, p:1, c:5, f:3,
     servings:[{n:'1 tbsp',g:20},{n:'2 tbsp',g:40}],
     tags:'sambal chilli paste spicy condiment malay belacan'},
    {name:'Coconut Milk / Santan (thick)', serving:100, cal:230, p:2.3, c:3.3, f:24,
     servings:[{n:'100ml',g:100},{n:'200ml',g:200}],
     tags:'santan coconut milk thick cream cooking malay curry'},
    {name:'Peanut Sauce (satay sauce)', serving:50, cal:215, p:7, c:10, f:17,
     servings:[{n:'2 tbsp',g:50}],
     tags:'peanut sauce satay kacang groundnut malay'},
    {name:'Oyster Sauce (1 tbsp)', serving:18, cal:51, p:1, c:10, f:0.1,
     servings:[{n:'1 tbsp',g:18},{n:'2 tbsp',g:36}],
     tags:'oyster sauce condiment chinese saus tiram cooking'}
  ];

  window.DEVFIT_LOCAL_FOODS = F;
})();
